### ISSUE TITLE
how to add Choices value to the questions?

### ISSUE THREAD

**Issue by NegassaB** [Salaah01/django-form-creator#1]
great work on this, I'm really enjoying it. I'm trying to add values to the Choices menu when inserting a question and I can't figure out a way to do it, Can you please help? 
Screenshots attached for better context

![Screenshot from 2022-06-18 18-28-51](https://user-images.githubusercontent.com/19590937/174444996-856bd756-be03-4387-97dc-28cb3eae8d26.png)
![Screenshot from 2022-06-18 18-28-43](https://user-images.githubusercontent.com/19590937/174444999-f3bcbd58-784f-43a4-80f1-ba0705c2c31a.png)
![Screenshot from 2022-06-18 18-28-35](https://user-images.githubusercontent.com/19590937/174445000-6d0fcf8c-591a-46f3-9a05-8807b8da6c35.png)

**Comment by Salaah01** [comment]
Hey NegassaB,
Thank you for your kind words.
The choices should be separated by pipes "|".
So in your case, the choices should be `1|2|3`.

I realise from your screenshot that there is no way of knowing. I've just pushed an update that should show you the help text from now all.
Run `pip install --upgrade django-form-creator`.
Thanks for giving the software a try and bringing this to my attention!
